#!/usr/bin/env bash
# Install nginx web server and redirect /redirect_me
# shellcheck disable=SC2154
apt-get -y update
apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i "/^\sserver_name.*/a\ \trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sed -i "/^\slocation.*/i\ \terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}\n" /etc/nginx/sites-available/default
sed -i "/^\slocation \/ {/i\ \tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
service nginx restart
