#!/usr/bin/env bash
# Install and configure HAproxy on your server
apt-get -y update
apt-get -y install haproxy
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend \
web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver \
78806-web-01 54.144.136.64:80 check\n\tserver 78806-web-02 100.24.236.179:80 \
check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
