#!/usr/bin/env bash
# Run nginx on all active IPs on port 8080 as user - nginx
pkill -9 apache2
chmod 777 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u "nginx" service nginx restart
